### ISSUE TITLE
Harta pe cartiere  

### ISSUE THREAD

**Issue by t-rolfin** [devfact/cmteb-failure-tracker#1]
Am gasit harta de mai jos, o pot face in format SVG. Vreau doar confirmarea daca este ceea ce cauti.

![harta](https://user-images.githubusercontent.com/70466418/118355014-7d6d1000-b576-11eb-8998-ccded37e130d.jpg)

**Comment by devfact** [comment]
Da, cam așa ceva aveam în minte. Mersi mult, nu mă așteptam să găsească cineva atât de repede :)
